### ISSUE TITLE
MTGAHelper executable does not run on Windows 7

### ISSUE THREAD

**Issue by t0nberryking** [ibiza240/MTGAHelper-Windows-Client#8]
Hi, I'm on Windows 7, MTGAHelper doesn't run via the exe or on startup. I have to go to cmd and use "dotnet" to run it (in which case it will run and perform fairly normally). Is there any way to fix this?

**Comment by ibiza240** [comment]
Hi, thanks for your feedback

This is a known issue and you found the workaround to still use it. The best you can do on top of that is to create a bat file containing the dotnet command and there's your shortcut to run the program, instead of having to type the command everytime.

We are actually looking for a way to fix this at the very moment :) Hopefully it will become available soon

**Comment by t0nberryking** [comment]
Yep, I've done that already. Glad that you guys are on top of it. Thanks!
